In [1]:
import pandas as pd

In [2]:
def normalize_dataframe(df):
    data_list = []

    for column in df.columns:
        if type(df[column][0]) == dict:
            data_list.append(pd.json_normalize(df[column]))
        else:
            data_list.append(df[column])    

    normalized_df = pd.concat(data_list, axis=1)

    return normalized_df

In [3]:
def print_dataframe_basic_info(df):

    print('\n')
    print('======================================================================')
    print('===================== CHECKING COLUMNS DATA TYPE =====================')
    print('======================================================================')
    print('\n')

    df.info()

    print('\n')
    print('======================================================================')
    print('============= SEARCHING FOR UNIQUE VALUES IN EACH COLUMN =============')
    print('======================================================================')
    print('\n')

    for column in df.columns:

        print(f'Column: {column}, Unique values: {df[column].unique()}')

In [4]:
file = 'data/Telco-Customer-Churn.json'
raw_df = pd.read_json(file)
raw_df

,customerID,Churn,customer,phone,internet,account
0,0002-ORFBO,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
1,0003-MKNFE,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
2,0004-TLHLJ,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
3,0011-IGKFF,Yes,"{'gender': 'Male', 'SeniorCitizen': 1, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
4,0013-EXCHZ,Yes,"{'gender': 'Female', 'SeniorCitizen': 1, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
...,...,...,...,...,...,...
7262,9987-LUTYD,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
7263,9992-RRAMN,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
7264,9992-UJOEL,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
7265,9993-LHIEB,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Two year', 'PaperlessBilling': '..."
7266,9995-HOTOH,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'No', 'MultipleLines': 'No ph...","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Two year', 'PaperlessBilling': '..."

In [5]:
normalized_df = normalize_dataframe(raw_df)
normalized_df

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.60,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.90,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.90,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.00,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.90,267.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,No,Female,0,No,No,13,Yes,No,DSL,...,No,No,Yes,No,No,One year,No,Mailed check,55.15,742.9
7263,9992-RRAMN,Yes,Male,0,Yes,No,22,Yes,Yes,Fiber optic,...,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10,1873.7
7264,9992-UJOEL,No,Male,0,No,No,2,Yes,No,DSL,...,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,50.30,92.75
7265,9993-LHIEB,No,Male,0,Yes,Yes,67,Yes,No,DSL,...,No,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85,4627.65
7266,9995-HOTOH,No,Male,0,Yes,Yes,63,No,No phone service,DSL,...,Yes,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00,3707.6

Desafios:

* Entender quais informaÃ§Ãµes o conjunto de dados possui.
* Analisar quais os tipos de dados.
* Verificar quais sÃ£o as inconsistÃªncias nos dados.
* Corrigir as inconsistÃªncias nos dados.
* Traduzir as colunas.
* Criar coluna de contas diÃ¡rias.

* Entender quais informaÃ§Ãµes o conjunto de dados possui.

O conjunto de dados possui informaÃ§Ãµes a respeito do perfil dos clientes fidelizados (ou nÃ£o) na empresa, contendo detalhes a respeito de seu sexo, idade, anos de contrato com a empresa e entre outros.

* Analisar quais os tipos de dados.

Os tipos dos dados da tabela podem ser verificados com o metodo "info()" do objeto dataframe da biblioteca pandas, retornando o tipo de dado de cada coluna da tabela de dados conforme segue:

* `customerID`: string, 10 chars
* `Churn`: string 'Yes' or 'No' or '' *** INCONSISTENCY FOUND
* `gender`: string 'male' or 'female'
* `SeniorCitizen`: integer 0 or 1 *** INCONSISTENCY FOUND
* `Partner`: string 'Yes' or 'No'
* `Dependents`: string 'Yes' or 'No'
* `tenure`: integer
* `PhoneService`: string 'Yes' or 'No'
* `MultipleLines`: string 'Yes' or 'No' or 'No phone service'
* `InternetService`: string 'DSL' or 'Fiber Optic' or 'No'
* `OnlineSecurity`: string 'Yes' or 'No' or 'No internet service'
* `OnlineBackup`: string 'Yes' or 'No' or 'No internet service'
* `DeviceProtection`: string 'Yes' or 'No' or 'No internet service'
* `TechSupport`: string 'Yes' or 'No' or 'No internet service'
* `StreamingTV`: string 'Yes' or 'No' or 'No internet service'
* `StreamingMovies`: string 'Yes' or 'No' or 'No internet service'
* `Contract`: string 'One year' or 'Month-to-month' or 'Two year'
* `PaperlessBilling`: string 'Yes' or 'No'
* `PaymentMethod`: string 'Mailed check' or 'Electronic check' or 'Credit card (automatic)' or 'Bank transfer (automatic)'
* `Charges.Monthly`: float
* `Charges.Total`: string *** INCONSISTENCY FOUND

In [6]:
print_dataframe_basic_info(normalized_df)

======================================================================
===================== CHECKING COLUMNS DATA TYPE =====================
======================================================================


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7267 non-null   object
 1   Churn             7267 non-null   object
 2   gender            7267 non-null   object
 3   SeniorCitizen     7267 non-null   int64
 4   Partner           7267 non-null   object
 5   Dependents        7267 non-null   object
 6   tenure            7267 non-null   int64
 7   PhoneService      7267 non-null   object
 8   MultipleLines     7267 non-null   object
 9   InternetService   7267 non-null   object
 10  OnlineSecurity    7267 non-null   object
 11  OnlineBackup      7267 non-null   object
 12  DeviceProtection  7267 non-null   object
 13  TechSupport       7267 non-null   object
 14  StreamingTV       7267 non-null   object
 15  StreamingMovies   7267 non-null   object
 16  Contract          7267 non-null   object
 17  PaperlessBilling  7267 non-null   object
 18  PaymentMethod     7267 non-null   object
 19  Charges.Monthly   7267 non-null   float64
 20  Charges.Total     7267 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.2+ MB


======================================================================
============= SEARCHING FOR UNIQUE VALUES IN EACH COLUMN =============
======================================================================


Column: customerID, Unique values: ['0002-ORFBO' '0003-MKNFE' '0004-TLHLJ' ... '9992-UJOEL' '9993-LHIEB'
 '9995-HOTOH']
Column: Churn, Unique values: ['No' 'Yes' '']
Column: gender, Unique values: ['Female' 'Male']
Column: SeniorCitizen, Unique values: [0 1]
Column: Partner, Unique values: ['Yes' 'No']
Column: Dependents, Unique values: ['Yes' 'No']
Column: tenure, Unique values: [ 9  4 13  3 71 63  7 65 54 72  5 56 34  1 45 50 23 55 26 69 11 37 49 66
 67 20 43 59 12 27  2 25 29 14 35 64 39 40  6 30 70 57 58 16 32 33 10 21
 61 15 44 22 24 19 47 62 46 52  8 60 48 28 41 53 68 51 31 36 17 18 38 42
  0]
Column: PhoneService, Unique values: ['Yes' 'No']
Column: MultipleLines, Unique values: ['No' 'Yes' 'No phone service']
Column: InternetService, Unique values: ['DSL' 'Fiber optic' 'No']
Column: OnlineSecurity, Unique values: ['No' 'Yes' 'No internet service']
Column: OnlineBackup, Unique values: ['Yes' 'No' 'No internet service']
Column: DeviceProtection, Unique values: ['No' 'Yes' 'No internet service']
Column: TechSupport, Unique values: ['Yes' 'No' 'No internet service']
Column: StreamingTV, Unique values: ['Yes' 'No' 'No internet service']
Column: StreamingMovies, Unique values: ['No' 'Yes' 'No internet service']
Column: Contract, Unique values: ['One year' 'Month-to-month' 'Two year']
Column: PaperlessBilling, Unique values: ['Yes' 'No']
Column: PaymentMethod, Unique values: ['Mailed check' 'Electronic check' 'Credit card (automatic)'
 'Bank transfer (automatic)']
Column: Charges.Monthly, Unique values: [65.6  59.9  73.9  ... 91.75 68.8  67.85]
Column: Charges.Total, Unique values: ['593.3' '542.4' '280.85' ... '742.9' '4627.65' '3707.6']

Corrigir inconsistencias em Churn

Corrigir inconsistencias em Senior Citzen

Corrigir inconsistencias em charges total

Traduzir Colunas

Criar coluna diarias